spring:
  datasource:
    url: jdbc:mysql://1.13.22.158:3306/xx_news?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: xxp2023
  redis:
    host: 1.13.22.158 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: lRuLa3Pfpd%WaKjYf # Redis服务器连接密码（默认为空）
    timeout: 300000ms # 连接超时时间（毫秒）

minio:
  endpoint: http://1.13.22.158:9090 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
  tempPath: /mydata/img/

logging:
  level:
    root: info
    com.xx.news.platform: info